services:
  - type: web
    name: stock-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

    envVars:
      - key: DRIVE_FILE_ID
        sync: false

    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1

    runtime:
      pythonVersion: 3.10

    timeout:
      request: 120